In [9]:
import pandas as pd

In [5]:
df=pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/arrhythmia/arrhythmia.data",header=None)
df

,0,1,2,3,4,5,6,7,8,9,...,270,271,272,273,274,275,276,277,278,279
0,75,0,190,80,91,193,371,174,121,-16,...,0.0,9.0,-0.9,0.0,0.0,0.9,2.9,23.3,49.4,8
1,56,1,165,64,81,174,401,149,39,25,...,0.0,8.5,0.0,0.0,0.0,0.2,2.1,20.4,38.8,6
2,54,0,172,95,138,163,386,185,102,96,...,0.0,9.5,-2.4,0.0,0.0,0.3,3.4,12.3,49.0,10
3,55,0,175,94,100,202,380,179,143,28,...,0.0,12.2,-2.2,0.0,0.0,0.4,2.6,34.6,61.6,1
4,75,0,190,80,88,181,360,177,103,-16,...,0.0,13.1,-3.6,0.0,0.0,-0.1,3.9,25.4,62.8,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
447,53,1,160,70,80,199,382,154,117,-37,...,0.0,4.3,-5.0,0.0,0.0,0.7,0.6,-4.4,-0.5,1
448,37,0,190,85,100,137,361,201,73,86,...,0.0,15.6,-1.6,0.0,0.0,0.4,2.4,38.0,62.4,10
449,36,0,166,68,108,176,365,194,116,-85,...,0.0,16.3,-28.6,0.0,0.0,1.5,1.0,-44.2,-33.2,2
450,32,1,155,55,93,106,386,218,63,54,...,-0.4,12.0,-0.7,0.0,0.0,0.5,2.4,25.0,46.6,1
451,78,1,160,70,79,127,364,138,78,28,...,0.0,10.4,-1.8,0.0,0.0,0.5,1.6,21.3,32.8,1

In [11]:
f=pd.read_csv(r"C:\Users\LENOVO\Desktop\arrhythmia 1.csv")
f

,Unnamed: 0,0,1,2,3,4,5,6,7,8,...,270,271,272,273,274,275,276,277,278,279
0,NaN,Age,Sex,Height,Weight,QRS duration,P-Rinterval,Q-T interval,T interval,Q-interval,...,V6,V6,V6,V6,V6,V6,V6,V6,V6,V6
1,0.0,75,0,190,80,91,193,371,174,121,...,0,9,-0.9,0,0,0.9,2.9,23.3,49.4,8
2,1.0,56,1,165,64,81,174,401,149,39,...,0,8.5,0,0,0,0.2,2.1,20.4,38.8,6
3,2.0,54,0,172,95,138,163,386,185,102,...,0,9.5,-2.4,0,0,0.3,3.4,12.3,49,10
4,3.0,55,0,175,94,100,202,380,179,143,...,0,12.2,-2.2,0,0,0.4,2.6,34.6,61.6,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
448,447.0,53,1,160,70,80,199,382,154,117,...,0,4.3,-5,0,0,0.7,0.6,-4.4,-0.5,1
449,448.0,37,0,190,85,100,137,361,201,73,...,0,15.6,-1.6,0,0,0.4,2.4,38,62.4,10
450,449.0,36,0,166,68,108,176,365,194,116,...,0,16.3,-28.6,0,0,1.5,1,-44.2,-33.2,2
451,450.0,32,1,155,55,93,106,386,218,63,...,-0.4,12,-0.7,0,0,0.5,2.4,25,46.6,1
452,451.0,78,1,160,70,79,127,364,138,78,...,0,10.4,-1.8,0,0,0.5,1.6,21.3,32.8,1

In [12]:
del f["Unnamed: 0"]

In [13]:
f

,0,1,2,3,4,5,6,7,8,9,...,270,271,272,273,274,275,276,277,278,279
0,Age,Sex,Height,Weight,QRS duration,P-Rinterval,Q-T interval,T interval,Q-interval,T interval,...,V6,V6,V6,V6,V6,V6,V6,V6,V6,V6
1,75,0,190,80,91,193,371,174,121,-16,...,0,9,-0.9,0,0,0.9,2.9,23.3,49.4,8
2,56,1,165,64,81,174,401,149,39,25,...,0,8.5,0,0,0,0.2,2.1,20.4,38.8,6
3,54,0,172,95,138,163,386,185,102,96,...,0,9.5,-2.4,0,0,0.3,3.4,12.3,49,10
4,55,0,175,94,100,202,380,179,143,28,...,0,12.2,-2.2,0,0,0.4,2.6,34.6,61.6,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
448,53,1,160,70,80,199,382,154,117,-37,...,0,4.3,-5,0,0,0.7,0.6,-4.4,-0.5,1
449,37,0,190,85,100,137,361,201,73,86,...,0,15.6,-1.6,0,0,0.4,2.4,38,62.4,10
450,36,0,166,68,108,176,365,194,116,-85,...,0,16.3,-28.6,0,0,1.5,1,-44.2,-33.2,2
451,32,1,155,55,93,106,386,218,63,54,...,-0.4,12,-0.7,0,0,0.5,2.4,25,46.6,1
452,78,1,160,70,79,127,364,138,78,28,...,0,10.4,-1.8,0,0,0.5,1.6,21.3,32.8,1

In [15]:
f.to_csv("arrhythmia 1.csv")